# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import categories_pb2 as categories__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cconfig.proto\x12\x08mycinema\x1a\x10categories.proto"\xe9\x03\n\x06Config\x12\x19\n\x11auto_scan_enabled\x18\x02 \x01(\x08\x12\'\n\x1fdelete_original_after_transcode\x18\x03 \x01(\x08\x12\x1b\n\x13idle_check_interval\x18\x04 \x01(\x05\x12\x18\n\x10watcher_interval\x18\x05 \x01(\x05\x12\x11\n\tcache_ttl\x18\x06 \x01(\x05\x12\x14\n\x0cmeta_workers\x18\x07 \x01(\x05\x12\x16\n\x0edetail_workers\x18\x08 \x01(\x05\x12\x16\n\x0emeta_cache_max\x18\t \x01(\x05\x12\x15\n\rgpu_transcode\x18\n \x01(\x08\x12\x13\n\x0bserver_port\x18\x0b \x01(\x05\x12\x13\n\x0bserver_host\x18\x0c \x01(\t\x12\x18\n\x10prefetch_enabled\x18\r \x01(\x08\x12\x19\n\x11cdn_cache_max_age\x18\x0e \x01(\x05\x12\x1c\n\x14l1_cache_max_size_mb\x18\x0f \x01(\x05\x12\x14\n\x0cl1_cache_ttl\x18\x10 \x01(\x05\x12\x16\n\x0eauto_transcode\x18\x13 \x01(\x08\x12,\n\x10default_category\x18\x11 \x01(\x0b2\x12.mycinema.Category\x12\x1b\n\x13uncategorized_label\x18\x12 \x01(\tB%Z#github.com/mycinema/protos;mycinemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/mycinema/protos;mycinema'
  _globals['_CONFIG']._serialized_start=45
  _globals['_CONFIG']._serialized_end=558
# @@protoc_insertion_point(module_scope)
