# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: export_info.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'export_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import categories_pb2 as categories__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65xport_info.proto\x12\x08mycinema\x1a\x10\x63\x61tegories.proto\"d\n\nExportInfo\x12&\n\ncategories\x18\x01 \x03(\x0b\x32\x12.mycinema.Category\x12\x19\n\x11\x61uto_scan_enabled\x18\x02 \x01(\x08\x12\x13\n\x0b\x65xport_time\x18\x03 \x01(\tB%Z#github.com/mycinema/protos;mycinemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'export_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/mycinema/protos;mycinema'
  _globals['_EXPORTINFO']._serialized_start=49
  _globals['_EXPORTINFO']._serialized_end=149
# @@protoc_insertion_point(module_scope)
