# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: series_cache.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'series_cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import categories_pb2 as categories__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12series_cache.proto\x12\x08mycinema\x1a\x10\x63\x61tegories.proto\"\x8b\x01\n\x0fSeriesCacheFile\x12\x31\n\x04\x64irs\x18\x01 \x03(\x0b\x32#.mycinema.SeriesCacheFile.DirsEntry\x1a\x45\n\tDirsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.mycinema.SeriesDirEntry:\x02\x38\x01\"\x81\x01\n\x0eSeriesDirEntry\x12\r\n\x05mtime\x18\x01 \x01(\x01\x12\'\n\x06single\x18\x02 \x01(\x0b\x32\x15.mycinema.SeriesEntryH\x00\x12(\n\x08multiple\x18\x03 \x01(\x0b\x32\x14.mycinema.SeriesListH\x00\x42\r\n\x0bseries_data\"2\n\nSeriesList\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.mycinema.SeriesEntry\"\x9b\x02\n\x0bSeriesEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x16\n\x0etotal_episodes\x18\x03 \x01(\x05\x12\x15\n\repisode_count\x18\x04 \x01(\x05\x12$\n\x06videos\x18\x05 \x03(\x0b\x32\x14.mycinema.VideoEntry\x12\r\n\x05\x63over\x18\x06 \x01(\t\x12\x13\n\x0borientation\x18\x07 \x01(\t\x12$\n\x08\x63\x61tegory\x18\x08 \x01(\x0b\x32\x12.mycinema.Category\x12\x0e\n\x06is_abs\x18\t \x01(\x08\x12\x10\n\x08\x61\x62s_path\x18\n \x01(\t\x12\x16\n\x0e\x66lat_base_path\x18\x0b \x01(\t\x12\x17\n\x0f\x63\x61tegory_merged\x18\x0c \x01(\x08\"p\n\nVideoEntry\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\x12\x11\n\tthumbnail\x18\x03 \x01(\t\x12\x12\n\nresolution\x18\x04 \x01(\t\x12\x17\n\x0fneeds_transcode\x18\x05 \x01(\x08\x42%Z#github.com/mycinema/protos;mycinemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'series_cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/mycinema/protos;mycinema'
  _globals['_SERIESCACHEFILE_DIRSENTRY']._loaded_options = None
  _globals['_SERIESCACHEFILE_DIRSENTRY']._serialized_options = b'8\001'
  _globals['_SERIESCACHEFILE']._serialized_start=51
  _globals['_SERIESCACHEFILE']._serialized_end=190
  _globals['_SERIESCACHEFILE_DIRSENTRY']._serialized_start=121
  _globals['_SERIESCACHEFILE_DIRSENTRY']._serialized_end=190
  _globals['_SERIESDIRENTRY']._serialized_start=193
  _globals['_SERIESDIRENTRY']._serialized_end=322
  _globals['_SERIESLIST']._serialized_start=324
  _globals['_SERIESLIST']._serialized_end=374
  _globals['_SERIESENTRY']._serialized_start=377
  _globals['_SERIESENTRY']._serialized_end=660
  _globals['_VIDEOENTRY']._serialized_start=662
  _globals['_VIDEOENTRY']._serialized_end=774
# @@protoc_insertion_point(module_scope)
