# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_meta_cache.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'video_meta_cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16video_meta_cache.proto\x12\x08mycinema\"\x9a\x01\n\x12VideoMetaCacheFile\x12:\n\x07\x65ntries\x18\x01 \x03(\x0b\x32).mycinema.VideoMetaCacheFile.EntriesEntry\x1aH\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.mycinema.VideoMetaEntry:\x02\x38\x01\"\x8c\x01\n\x0eVideoMetaEntry\x12\r\n\x05mtime\x18\x01 \x01(\x03\x12\x13\n\x0borientation\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x12\n\nresolution\x18\x05 \x01(\t\x12\x11\n\tfile_size\x18\x06 \x01(\x03\x12\x10\n\x08\x64uration\x18\x07 \x01(\x01\x42%Z#github.com/mycinema/protos;mycinemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_meta_cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/mycinema/protos;mycinema'
  _globals['_VIDEOMETACACHEFILE_ENTRIESENTRY']._loaded_options = None
  _globals['_VIDEOMETACACHEFILE_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_VIDEOMETACACHEFILE']._serialized_start=37
  _globals['_VIDEOMETACACHEFILE']._serialized_end=191
  _globals['_VIDEOMETACACHEFILE_ENTRIESENTRY']._serialized_start=119
  _globals['_VIDEOMETACACHEFILE_ENTRIESENTRY']._serialized_end=191
  _globals['_VIDEOMETAENTRY']._serialized_start=194
  _globals['_VIDEOMETAENTRY']._serialized_end=334
# @@protoc_insertion_point(module_scope)
